### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by SchellerCyberSecurity** [awfullyniceguy/esm_api#1]
When using your python script I keep getting the following error:

Traceback (most recent call last):
  File "ViewWatchlists.py", line 16, in <module>
    authenticated_header = esm_api.login_esm(usr, pswd, esm_ipaddress)
  File "/Users/dscheller/Documents/McAfee_Python/esm_api.py", line 58, in login_esm
    authenticated_header["Cookie"] = jwttoken[0].strip()
IndexError: list index out of range

**Comment by awfullyniceguy** [comment]
That could be the password expired in ESM or your host not being able to reach it, the error is it's not able to find the Cookie in the Response. Can you debug it by adding some print statements and see what the response is from the Server?

**Comment by SchellerCyberSecurity** [comment]
I got it fixed, I was using the wrong creds.

Derek M Scheller Jr
CCNA R/S, CCNA-Security, CISSP, CEH, CPT, GSEC, GCED, GCIH, GPYC
Cell: 443-805-0239
https://schellercybersecurity.com/blog
